name = "starkid-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "starkid-production"
database_id = "your-production-database-id"

# R2 存储绑定
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "starkid-images"

# 环境变量
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-jwt-secret-key-change-this-in-production"
JWT_EXPIRES_IN = "7d"
CORS_ORIGIN = "https://your-frontend-domain.com"
MAX_FILE_SIZE = "5242880"  # 5MB
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp"

# 开发环境配置
[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "starkid-development"
database_id = "your-development-database-id"

[env.development.vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:5173"
JWT_SECRET = "dev-jwt-secret-key"